name: _Release Solution  
on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
            description: 'The environment to deploy to. E.g., dev, tst, prd'
        
jobs:
  build:
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUNBUFFERED: 1
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      VSO_FORCE_UTF8_OUTPUT: true
      TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
      CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}

    steps:
          
      - name: Download Automation artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: automation
          path: ./automation/
    
      - name: Download Solution artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: solution
          path: ./solution/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automation/resources/requirements.txt

      - name: Release Fabric items
        run: python -u automation/scripts/fabric_release.py --environment ${{ inputs.environment }} --repo_path "./solution"

      - name: Generate SQL connection string
        id: generate_connection
        shell: bash
        run: |
          python automation/scripts/generate_connection_string.py \
            --client_id "${CLIENT_ID}" \
            --client_secret "${CLIENT_SECRET}" \
            --environment "${{ inputs.environment }}" \
            --layer "Core" \
            --database "Metadata" \
            --output_file conn.txt
          echo "connection_string=$(cat conn.txt)" >> $GITHUB_OUTPUT

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.2.1
        with:
          connection-string: ${{ steps.generate_connection.outputs.connection_string }}
          path: './solution/core/Metadata.SQLDatabase/bin/Debug/Metadata.dacpac'
          action: publish
          arguments: '/p:DropObjectsNotInSource=false'