name: Fabric Feature - Cleanup

on:
  pull_request:
    branches:
    - main
    types: [closed]

jobs:
  cleanup-feature:
    name: Cleanup Fabric Feature Workspaces
    runs-on: ubuntu-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUNBUFFERED: 1
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      VSO_FORCE_UTF8_OUTPUT: true'
      TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
      CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r automation/resources/requirements.txt

      - name: Run Fabric feature maintenance script
        run: |
          python -u automation/scripts/fabric_feature_maintainance.py \
            --branch_name ${{ github.head_ref }} \
            --action delete